name: ETL Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL script
      env:
        RAWG_API_KEY: ${{ secrets.RAWG_API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        DB_NAME: SSN_ETL_assignment
        COLLECTION_NAME: rawg_platforms_processed
      run: |
        python etl_connector.py
